services:
  - type: web
    name: n8n
    env: node
    buildCommand: |
      npm install -g pnpm@latest
      pnpm install --frozen-lockfile
      pnpm run build
    startCommand: pnpm start
    nodeVersion: 20.15.0
